---
libvirt_pool_name: "default"
libvirt_pool_path: "/var/lib/libvirt/images"
libvirt_network_name: "default"

ubuntu_cloud_image_name: "noble-server-cloudimg-amd64.img"
ubuntu_cloud_image_url: >-
  https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

libvirt_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - virtinst
  - libguestfs-tools
  - python3-libvirt
  - python3-lxml
