---
ssh_port: 22
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_x11_forwarding: "no"
ssh_max_auth_tries: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_fail2ban_enabled: true
ssh_fail2ban_maxretry: 5
ssh_fail2ban_bantime: 3600
