---
hypervisor_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - virtinst
  - libguestfs-tools
  - python3-libvirt
  - python3-lxml

hypervisor_pool_name: "default"
hypervisor_pool_path: "/var/lib/libvirt/images"
hypervisor_network_name: "default"
hypervisor_ssh_key_type: "ed25519"

hypervisor_ubuntu_cloud_image_name: "noble-server-cloudimg-amd64.img"
hypervisor_ubuntu_cloud_image_url: >-
  https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
