services:
  devcontainer:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: .devcontainer/full/Dockerfile
      args:
        VARIANT: base:ubuntu-24.04
    volumes:
      - ../../:/workspace:cached
    command: sleep infinity
