---
# ---------------------------------------------------------------------------
# vm-base-dev-onprem-01 â€“ First base infrastructure VM
# ---------------------------------------------------------------------------
ansible_host: 192.168.122.11
vm_vcpus: 2
vm_memory_mb: 2048
vm_disk_gb: 20
