---
galaxy_info:
  author: levendaal
  description: Install and configure KVM/libvirt hypervisor, generate SSH keypair
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
    - name: Debian
      versions: [bookworm]
dependencies: []
