name: OpenTofu Destroy
description: Destroy OpenTofu-managed infrastructure from a given directory

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2:00 UTC
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  destroy:
    name: Destroy ${{ inputs.artifact_name }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.client_id }}
          tenant-id: "90d27970-b92c-43dc-9935-1ed557d8e20e"
          allow-no-subscriptions: true

      - name: Install OpenTofu
        uses: ./.github/actions/opentofu-install
        with:
          tofu_version: 1.8.0

      - name: Initialize OpenTofu
        uses: ./.github/actions/opentofu-init
        with:
          working_directory: ${{ inputs.working_directory }}
          state_key: ${{ inputs.state_key }}

      - name: Destroy resources
        id: destroy
        uses: ./.github/actions/opentofu-destroy
        with:
          working_directory: ${{ inputs.working_directory }}

      - name: Post Destroy Result to PR
        if: always()
        uses: ./.github/actions/opentofu-apply-comment
        with:
          apply_output_file: ${{ steps.destroy.outputs.destroy_output_file }}
          environment: ${{ inputs.artifact_name }}
          working_directory: ${{ inputs.working_directory }}
          apply_status: ${{ steps.destroy.outcome }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
